// <auto-generated />
using System;
using FIAP14NET.Receita.Site.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIAP14NET.Receita.Site.Migrations
{
    [DbContext(typeof(ReceitaContexto))]
    [Migration("20190403135421_Migracao_001")]
    partial class Migracao_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FIAP14NET.Receita.Site.Dominio.Entidades.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AlteradoEm")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasColumnType("varchar")
                        .HasMaxLength(100);

                    b.Property<Guid?>("ReceitaId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("FIAP14NET.Receita.Site.Dominio.Entidades.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AlteradoEm")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar")
                        .HasMaxLength(300);

                    b.Property<string>("ModoDePreparo")
                        .HasColumnType("varchar")
                        .HasMaxLength(3000);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("FIAP14NET.Receita.Site.Dominio.Entidades.Ingrediente", b =>
                {
                    b.HasOne("FIAP14NET.Receita.Site.Dominio.Entidades.Receita")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
